# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-01 18:58
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801')),
                ('location_type', models.PositiveSmallIntegerField(choices=[(1, '\u5934\u90e8'), (2, '\u4e2d\u90e8'), (3, '\u5e95\u90e8')], default=1, verbose_name='\u663e\u793a\u4f4d\u7f6e')),
                ('image', models.ImageField(upload_to=common.models.image_upload_to, verbose_name='\u56fe\u7247')),
                ('redirect_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WEB\u9875\u9762'), (2, '\u6d3b\u52a8\u8be6\u60c5')], null=True, verbose_name='\u8df3\u8f6c\u7c7b\u578b')),
                ('detail_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8be6\u60c5ID\u6216URL')),
                ('valid', models.BooleanField(default=0, verbose_name='\u662f\u5426\u6709\u6548')),
                ('sort', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='\u952e')),
                ('value', models.TextField(blank=True, verbose_name='\u503c')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u7cfb\u7edf\u914d\u7f6e',
                'verbose_name_plural': '\u7cfb\u7edf\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='ServiceTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6761\u6b3e\u5185\u5bb9')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u670d\u52a1\u6761\u6b3e',
                'verbose_name_plural': '\u670d\u52a1\u6761\u6b3e',
            },
        ),
        migrations.CreateModel(
            name='VersionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7248\u672c\u540d\u79f0')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='\u7248\u672c\u7f16\u7801')),
                ('can_preview_page', models.BooleanField(default=True, verbose_name='\u662f\u5426\u652f\u6301\u8bd5\u542c\u9875\u9762')),
                ('can_customize_city', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u6301\u81ea\u5b9a\u4e49\u57ce\u5e02')),
                ('can_customize_logo', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u6301\u81ea\u5b9a\u4e49Logo')),
                ('valid_days', models.PositiveIntegerField(default=0, verbose_name='\u6709\u6548\u5929\u6570')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c\uff08\u5143/\u6b21\uff09')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u7248\u672c\u7c7b\u578b',
                'verbose_name_plural': '\u7248\u672c\u7c7b\u578b',
            },
        ),
    ]
