# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('people', '0005_auto_20180901_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(db_index=True, max_length=20, verbose_name='\u8ba2\u5355\u53f7')),
                ('transaction_id', models.CharField(db_index=True, default='', max_length=50, verbose_name='\u5fae\u4fe1\u652f\u4ed8ID')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='\u5907\u6ce8')),
                ('description', models.TextField(default='', verbose_name='\u8ba2\u5355\u8bb0\u5f55\u63cf\u8ff0')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='\u8d2d\u4e70\u5546\u54c1\u6570\u91cf')),
                ('amount_display', models.FloatField(default=0.0, help_text='\u4ee5\u4eba\u6c11\u5e01\u5143\u4e3a\u5355\u4f4d', verbose_name='\u53d8\u52a8\u91d1\u989d')),
                ('amount_cents', models.IntegerField(default=0, help_text='\u4ee5\u4eba\u6c11\u5e01\u5206\u4e3a\u5355\u4f4d', verbose_name='\u53d8\u52a8\u91d1\u989d\uff08\u8ba1\u7b97\u7528\uff09')),
                ('status', models.SmallIntegerField(choices=[(1, '\u65b0\u4e8b\u52a1'), (2, '\u5df2\u5173\u95ed'), (3, '\u5df2\u5b8c\u6210')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('pay_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5fae\u4fe1\u652f\u4ed8\u7684\u652f\u4ed8URL')),
                ('pay_image', models.ImageField(blank=True, null=True, upload_to=order.models.pay_qr_image_upload_to, verbose_name='\u5fae\u4fe1\u652f\u4ed8\u7684\u4e8c\u7ef4\u7801')),
                ('is_refunded', models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u9000\u6b3e')),
                ('dt_granted', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.CustomUser', verbose_name='\u7528\u6237')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.VersionCategory', verbose_name='\u7248\u672c\u7c7b\u578b')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True, verbose_name='\u7f16\u7801')),
                ('item_pid', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u56fd\u5bb6ID')),
                ('item_pname', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u56fd\u5bb6\u540d\u79f0')),
                ('item_id', models.PositiveIntegerField(verbose_name='\u57ce\u5e02ID')),
                ('item_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u57ce\u5e02\u540d\u79f0')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=order.models.logo_upload_to, verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slogan')),
                ('succeed', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6210\u529f')),
                ('url', models.CharField(max_length=256, verbose_name='web app\u8df3\u8f6c\u5730\u5740')),
                ('image', models.ImageField(blank=True, upload_to=order.models.qr_image_upload_to, verbose_name='web app\u8df3\u8f6c\u5730\u5740\u7684\u4e8c\u7ef4\u7801')),
                ('viewed_count', models.PositiveIntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='\u4e0b\u8f7d\u91cf')),
                ('dt_expired', models.DateTimeField(blank=True, null=True, verbose_name='\u5931\u6548\u4e8e')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.CustomUser', verbose_name='\u7528\u6237')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.VersionCategory', verbose_name='\u7248\u672c\u7c7b\u578b')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u8d2d\u4e70\u9879\u76ee',
                'verbose_name_plural': '\u8d2d\u4e70\u9879\u76ee',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=64, verbose_name='\u9000\u6b3e\u8ba2\u5355\u53f7')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='\u652f\u4ed8\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u9000\u6b3e\u8ba2\u5355',
                'verbose_name_plural': '\u9000\u6b3e\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='UniqueOrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='\u552f\u4e00\u7f16\u7801')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
            ],
        ),
    ]
