# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(default=0, help_text='unit: mei', verbose_name='virtual balance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='devicetoken',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='devicetoken'),
        ),
    ]
