# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20171203_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': 'user platform',
                'verbose_name_plural': 'user platforms',
            },
        ),
        migrations.CreateModel(
            name='UserPlatformShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=512, verbose_name='user platform identifier')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='people.Platform', verbose_name='platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='people.CustomUser', verbose_name='user')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': 'user platform ship',
                'verbose_name_plural': 'user platform ship',
            },
        ),
    ]
