# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_platform_userplatformship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u540d\u79f0')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u4e1a\u52a1\u7c7b\u578b',
                'verbose_name_plural': '\u4e1a\u52a1\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Business', verbose_name='\u4e1a\u52a1\u7c7b\u578b')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': '\u7528\u6237\u4e1a\u52a1\u7c7b\u578b',
                'verbose_name_plural': '\u7528\u6237\u4e1a\u52a1\u7c7b\u578b',
            },
        ),
        migrations.RemoveField(
            model_name='userplatformship',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='userplatformship',
            name='user',
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458',
                'proxy': True,
                'verbose_name_plural': '\u7ba1\u7406\u5458',
            },
            bases=('people.customuser',),
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': 'id', 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AlterModelOptions(
            name='userauthority',
            options={'get_latest_by': 'id', 'verbose_name': '\u7528\u6237\u6743\u9650', 'verbose_name_plural': '\u7528\u6237\u6743\u9650'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'get_latest_by': 'id', 'verbose_name': '\u7528\u6237\u89d2\u8272', 'verbose_name_plural': '\u7528\u6237\u89d2\u8272'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': '\u7528\u6237Token', 'verbose_name_plural': '\u7528\u6237Token'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'get_latest_by': 'id', 'verbose_name': '\u7528\u6237\u7c7b\u578b', 'verbose_name_plural': '\u7528\u6237\u7c7b\u578b'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='constellation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='devicetoken',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remind_content',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vip_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vip_remind',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vip_start',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='device_uuid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='\u7f16\u7801'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.UserAuthority', verbose_name='\u7528\u6237\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.user_avatar_upload_to, verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='\u8bf7\u4f7f\u7528 \'[algo]$[salt]$[hexdigest]\' \u8fd9\u6837\u7684\u5bc6\u7801\u683c\u5f0f\uff0c\u6216\u8005 <a href="password/">\u70b9\u51fb\u6b64\u5904</a> \u4fee\u6539\u8be5\u7528\u6237\u767b\u5f55\u5bc6\u7801\u3002', max_length=128, verbose_name='\u767b\u5f55\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.UserRole', verbose_name='\u7528\u6237\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.UserType', verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='userauthority',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='userauthority',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='userauthority',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e'),
        ),
        migrations.AlterField(
            model_name='userauthority',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='people.CustomUser', verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='UserPlatformShip',
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='people.CustomUser', verbose_name='\u7528\u6237'),
        ),
    ]
