# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_platform_userplatformship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.user_update_avatar_to, verbose_name='avatar'),
        ),
    ]
